language: java

# enable container-based architecture and caching
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'

jdk:
  - oraclejdk8 # JavaFX 8 only works under Oracle JDK 8

# allow GUI testing
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
